### ISSUE TITLE
Generic HMI backend server not running on Ubuntu 16

### ISSUE THREAD

**Issue by ShobhitAd** [smartdevicelink/generic_hmi#374]
### Bug Report
Running the backend server (using `./deploy_server.sh`) results in an error on Ubuntu 16

The websockets library version (8.1) we're using requires a min python version of `3.6` but Ubuntu 16 has `3.5.2` as the default python3 version. 

Ubuntu 16 users would be required to upgrade to python3.6 (or higher) manually

##### Reproduction Steps
1. Install generic hmi dependencies https://github.com/smartdevicelink/generic_hmi/tree/release/0.10.0_RC1#dependencies
2. Run `./deploy_server.sh`

##### Expected Behavior
The backend server starts without any errors.

##### Observed Behavior
The backend server fails to start with the following error
```
Starting HMI Backend service...
Traceback (most recent call last):
  File "./python_websocket/src/start_server.py", line 33, in <module>
    import websockets
  File ".../generic_hmi/python_websocket/src/websockets/__init__.py", line 3, in <module>
    from .auth import *  # noqa
  File ".../generic_hmi/python_websocket/src/websockets/auth.py", line 43
    **kwargs: Any,
                 ^
SyntaxError: invalid syntax
HMI Backend service was stopped
```

**Comment by ShobhitAd** [comment]
Closed via #372
